@echo off
echo Cleaning git locks...
if exist .git\index.lock del /f .git\index.lock
echo Adding corrected files...
git add lib/toast.ts public/locales
echo Committing changes...
git commit -m "Final build and translation fix"
echo Pushing to GitHub...
git push origin main
echo Done! Please check Vercel build status.
pause
